[package]
name = "leaky-bucket"
version = "0.11.1"
authors = ["John-John Tedro <udoprog@tedro.se>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/udoprog/leaky-bucket"
homepage = "https://github.com/udoprog/leaky-bucket"
documentation = "https://docs.rs/leaky-bucket"
description = """
Futures-aware rate limiter implementation.
"""
categories = ["algorithms", "network-programming", "concurrency"]

[dependencies]
parking_lot = "0.11.1"
tokio = { version = "1", features = ["time"] }
tracing = "0.1.26"

[dev-dependencies]
anyhow = "1.0.40"
futures = "0.3"
helpers = { path = "helpers" }
pin-project = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "rt", "time"] }
